main:
  - name: 关于
    url: '#about'
    weight: 1
  - name: 发布
    url: /posts/
    weight: 2
  - name: 文档
    url: /docs/
    weight: 3
  - name: 学校官网
    url: /school/
    weight: 4
  - name: 状态
    url: https://status.xuanxuan1231.tk
    weight: 5