main:
  - name: 本站支持IPv6
    weight: 1
  - name: 关于
    url: '#about'
    weight: 2
  - name: 发布
    url: /posts/
    weight: 3
  - name: 文档
    url: /docs/
    weight: 4
  - name: 用户文档
    url: https://xuanxuan1231.github.io