mainSections:
  - posts
description: Eureka is a elegant and powerful theme for Hugo.

repoEditURL:

dateFormat:

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme:

# Colors and fonts. Default style is data/styles/default.yaml/
style:

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/icon.png
publisherName: WANG Chucheng
publisherLogo:

highlight:
  handler: highlightjs

  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/main/build/languages for available languages.
    languages:
      - dart
    # See https://github.com/highlightjs/cdn-release/tree/main/build/styles for available styles.
    style: base16/solarized-light

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

comment:
  # Options: disqus, commento, valine and utterances.
  handler: giscus

  # disqus:
    # shortname: class3-26

  # utterances:
  #   # Browse https://utteranc.es/ to see the options available.
  #   # If you want the color scheme of utterances to follow eureka's, you can set `theme: eureka`.
  #   repo: xuanxuan1231/class3-26
  #   issue-term:
  #   theme: eureka

  # commento:
  #   # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty.
  #   url:

#   valine:
  #   # Browse https://valine.js.org/en/configuration.html to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `appId` should be written as `app-Id` or other acceptable formats.
  #   app-Id: -U-Y-W-Xdl6wpqpfr-J-Zas-Yoh0pm-N gz-Gzo-Hsz
  #   app-Key: 6o-Mj-A-X4-H3-N-M-T-V6i2u-Lcub-L-Cf
  # enableGiscus: true # enable giscus for comment
  giscus:
    data_repo: xuanxuan1231/class3-26
    data_repo_id: R_kgDOKZdYaw
    data_category: Announcements
    data_category_id: DIC_kwDOKZdYa84CZ5CZ
    data_mapping: title
    data_strict: 0
    data_reactions_enabled: 1
    data_emit_metadata: 0
    data_input_position: bottom
    data_theme: eureka
    data_lang: zh-CN
    crossorigin: anonymous
    # theme: eureka
  # go to https://giscus.app to get configuraion

diagram:
  handler: mermaid

  # mermaid:
  #   # Browse https://mermaid-js.github.io/mermaid/#/Setup to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `diagramPadding` should be written as `diagram-Padding` or other acceptable formats.
  #   theme: 
  #   flowchart:
  #     diagram-padding:

# enableGitalk: false #
# gitalk: 
#   clientID: 6db8e416ed9ab725c521 # 您刚才创建Github Application 的 Client ID
#   clientSecret : 50e05e01fb2c599f37817808891e960812b5c985 # 您刚才创建Github Application 的 Client Secret
#   repo : class3-26 # 您的博客的github地址Repository name，例如：xxxx.github.io
#   owner : xuanxuan1231 # 您的GitHub ID
#   admin: xuanxuan1231 # 您的GitHub ID
#   id: location.pathname # 文章页面的链接地址就是ID
#   labels: gitalk # Github issue labels. If you used to use Gitment, you can change it
#   perPage: 15 # Pagination size, with maximum 100.
#   pagerDirection: last # Comment sorting direction, available values are 'last' and 'first'.
#   createIssueManually: true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
#   distractionFreeMode: false # Enable hot key (cmd|ctrl + enter) submit comment.
